/*
 * File: app/model/AssigningOrderForDelivery.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cobuy.model.AssigningOrderForDelivery', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.Field'
    ],

    fields: [
        {
            name: 'member_id'
        },
        {
            name: 'order_id'
        },
        {
            name: 'status'
        },
        {
            name: 'failed_remark'
        },
        {
            name: 'ondispute_remark'
        },
        {
            name: 'delivered_remark'
        },
        {
            name: 'ontransit_remark'
        },
        {
            name: 'ontransit_commencement_date',
            type: 'date'
        },
        {
            name: 'delivery_return_date',
            type: 'date'
        },
        {
            name: 'order_assigned_by'
        },
        {
            name: 'order_assigned_to'
        },
        {
            name: 'date_of_assignment',
            type: 'date'
        }
    ]
});