/*
 * File: app/model/BankCollectForCountry.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cobuy.model.BankCollectForCountry', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.Field'
    ],

    fields: [
        {
            name: 'bank_id'
        },
        {
            name: 'country_id'
        },
        {
            name: 'status'
        },
        {
            name: 'payment_mode'
        },
        {
            name: 'approved'
        },
        {
            name: 'approved_user_id'
        },
        {
            name: 'disapproved_user_id'
        },
        {
            name: 'activated_user_id'
        },
        {
            name: 'activated_time',
            type: 'date'
        },
        {
            name: 'approved_time',
            type: 'date'
        },
        {
            name: 'disapproved_time',
            type: 'date'
        },
        {
            name: 'initiator_create_time',
            type: 'date'
        },
        {
            name: 'initiator_update_time',
            type: 'date'
        },
        {
            name: 'initiator_create_user_id'
        },
        {
            name: 'initiator_update_user_id'
        }
    ]
});