/*
 * File: app/model/City.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cobuy.model.City', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.Field'
    ],

    fields: [
        {
            name: 'id'
        },
        {
            name: 'name'
        },
        {
            name: 'description'
        },
        {
            name: 'state_id'
        },
        {
            name: 'zip_code'
        },
        {
            name: 'city_number'
        },
        {
            name: 'top_priority_delivery_in_percentage',
            type: 'float'
        },
        {
            name: 'priority_delivery_in_percentage',
            type: 'float'
        },
        {
            name: 'standard_delivery_in_percentage',
            type: 'float'
        },
        {
            name: 'minimum_top_priority_delivery_amount',
            type: 'float'
        },
        {
            name: 'minimum_priority_delivery_amount',
            type: 'float'
        },
        {
            name: 'minimum_standard_delivery_amount',
            type: 'float'
        },
        {
            name: 'estimated_number_of_days_for_top_priority_delivery',
            type: 'int'
        },
        {
            name: 'estimated_number_of_days_for_priority_delivery',
            type: 'int'
        },
        {
            name: 'estimated_number_of_days_for_standard_delivery',
            type: 'int'
        },
        {
            name: 'accept_payment_on_delivery',
            type: 'boolean'
        },
        {
            name: 'create_time',
            type: 'date'
        },
        {
            name: 'update_time',
            type: 'date'
        },
        {
            name: 'create_user_id'
        },
        {
            name: 'update_user_id'
        }
    ]
});