/*
 * File: app/model/HamperContainers.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cobuy.model.HamperContainers', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.Field'
    ],

    fields: [
        {
            name: 'id'
        },
        {
            name: 'name'
        },
        {
            name: 'description'
        },
        {
            name: 'amount',
            type: 'float'
        },
        {
            name: 'service_charge_in_percentages',
            type: 'float'
        },
        {
            name: 'minimum_service_charge',
            type: 'float'
        },
        {
            name: 'weight',
            type: 'float'
        },
        {
            name: 'code'
        },
        {
            name: 'icon'
        },
        {
            name: 'create_time'
        },
        {
            name: 'update_time'
        },
        {
            name: 'create_user_id'
        },
        {
            name: 'update_user_id'
        }
    ]
});