/*
 * File: app/model/Order.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cobuy.model.Order', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.Field'
    ],

    fields: [
        {
            name: 'id'
        },
        {
            name: 'order_number'
        },
        {
            name: 'status'
        },
        {
            name: 'delivery_address1'
        },
        {
            name: 'delivery_address2'
        },
        {
            name: 'delivery_city_id'
        },
        {
            name: 'delivery_state_id'
        },
        {
            name: 'delivery_country_id'
        },
        {
            name: 'delivery_mobile_number'
        },
        {
            name: 'address_landmark'
        },
        {
            name: 'nearest_bus_stop'
        },
        {
            name: 'person_in_care_of'
        },
        {
            name: 'order_initiation_date',
            type: 'date'
        },
        {
            name: 'last_updated_date',
            type: 'date'
        },
        {
            name: 'order_initiated_by'
        },
        {
            name: 'order_updated_by'
        }
    ]
});