/*
 * File: app/model/ProductConstituent.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cobuy.model.ProductConstituent', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.Field'
    ],

    fields: [
        {
            name: 'id'
        },
        {
            name: 'name'
        },
        {
            name: 'description'
        },
        {
            name: 'feature'
        },
        {
            name: 'specifications'
        },
        {
            name: 'product_id'
        },
        {
            name: 'condition'
        },
        {
            name: 'icon'
        },
        {
            name: 'headline_image'
        },
        {
            name: 'product_front_view'
        },
        {
            name: 'product_right_side_view'
        },
        {
            name: 'product_top_view'
        },
        {
            name: 'product_inside_view'
        },
        {
            name: 'product_engine_view'
        },
        {
            name: 'product_back_view'
        },
        {
            name: 'product_left_side_view'
        },
        {
            name: 'product_bottom_view'
        },
        {
            name: 'product_dashboard_view'
        },
        {
            name: 'product_contents_or_booth_view'
        },
        {
            name: 'icon_size'
        },
        {
            name: 'cost_price',
            type: 'float'
        },
        {
            name: 'prevailing_retail_selling_price',
            type: 'float'
        },
        {
            name: 'maximum_portion',
            type: 'int'
        },
        {
            name: 'per_portion_price',
            type: 'float'
        },
        {
            name: 'discount_rate',
            type: 'float'
        },
        {
            name: 'discounted_amount',
            type: 'float'
        },
        {
            name: 'quantity',
            type: 'int'
        },
        {
            name: 'quantity_of_product_in_the_pack',
            type: 'int'
        },
        {
            name: 'displayable_on_store',
            type: 'boolean'
        },
        {
            name: 'create_time',
            type: 'date'
        },
        {
            name: 'create_user_id',
            type: 'int'
        },
        {
            name: 'update_time',
            type: 'date'
        },
        {
            name: 'update_user_id',
            type: 'int'
        },
        {
            name: 'minimum_number_of_product_to_buy'
        },
        {
            name: 'whats_in_a_park'
        },
        {
            name: 'whats_product_per_item'
        },
        {
            name: 'price_validity_period'
        },
        {
            name: 'brand'
        },
        {
            name: 'maker'
        },
        {
            name: 'origin'
        },
        {
            name: 'start_price_validity_period',
            type: 'date'
        },
        {
            name: 'end_price_validity_period',
            type: 'date'
        }
    ]
});