/*
 * File: app/model/Products.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cobuy.model.Products', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.Field'
    ],

    fields: [
        {
            name: 'id'
        },
        {
            name: 'name'
        },
        {
            name: 'description'
        },
        {
            name: 'feature'
        },
        {
            name: 'specifications'
        },
        {
            name: 'service_id'
        },
        {
            name: 'category_id'
        },
        {
            name: 'product_type_id'
        },
        {
            name: 'condition'
        },
        {
            name: 'icon'
        },
        {
            name: 'product_front_view'
        },
        {
            name: 'product_right_side_view'
        },
        {
            name: 'product_top_view'
        },
        {
            name: 'product_inside_view'
        },
        {
            name: 'product_engine_view'
        },
        {
            name: 'product_back_view'
        },
        {
            name: 'product_left_side_view'
        },
        {
            name: 'product_bottom_view'
        },
        {
            name: 'product_dashboard_view'
        },
        {
            name: 'product_contents_or_booth_view'
        },
        {
            name: 'headline_image'
        },
        {
            name: 'icon_size'
        },
        {
            name: 'cost_price',
            type: 'float'
        },
        {
            name: 'prevailing_retail_selling_price',
            type: 'float'
        },
        {
            name: 'maximum_portion',
            type: 'int'
        },
        {
            name: 'per_portion_price',
            type: 'float'
        },
        {
            name: 'discount_rate',
            type: 'float'
        },
        {
            name: 'discounted_amount',
            type: 'float'
        },
        {
            name: 'quantity',
            type: 'int'
        },
        {
            name: 'displayable_on_store',
            type: 'boolean'
        },
        {
            name: 'is_quotable',
            type: 'boolean'
        },
        {
            name: 'is_available',
            type: 'boolean'
        },
        {
            name: 'is_escrowable',
            type: 'boolean'
        },
        {
            name: 'is_future_tradable',
            type: 'boolean'
        },
        {
            name: 'create_time',
            type: 'date'
        },
        {
            name: 'create_user_id'
        },
        {
            name: 'update_time',
            type: 'date'
        },
        {
            name: 'update_user_id'
        },
        {
            name: 'minimum_number_of_product_to_buy'
        },
        {
            name: 'whats_in_a_park'
        },
        {
            name: 'whats_product_per_item'
        },
        {
            name: 'price_validity_period'
        },
        {
            name: 'brand'
        },
        {
            name: 'maker'
        },
        {
            name: 'origin'
        },
        {
            name: 'start_price_validity_period',
            type: 'date'
        },
        {
            name: 'end_price_validity_period',
            type: 'date'
        },
        {
            name: 'is_a_hamper',
            type: 'boolean'
        },
        {
            name: 'is_custom_product',
            type: 'boolean'
        },
        {
            name: 'is_payment_permitted_on_delivery',
            type: 'boolean'
        },
        {
            name: 'is_with_video',
            type: 'boolean'
        },
        {
            name: 'video_for',
            type: 'string'
        },
        {
            name: 'video_filename',
            type: 'string'
        },
        {
            name: 'video_size',
            type: 'float'
        },
        {
            name: 'weight',
            type: 'float'
        },
        {
            name: 'code',
            type: 'string'
        },
        {
            name: 'hamper_cost_limit',
            type: 'float'
        },
        {
            name: 'hamper_container_id',
            type: 'float'
        },
        {
            name: 'is_rentable',
            type: 'boolean'
        },
        {
            name: 'is_paas',
            type: 'boolean'
        },
        {
            name: 'is_faas',
            type: 'boolean'
        },
        {
            name: 'rent_cost_per_day',
            type: 'float'
        },
        {
            name: 'maximum_rent_quantity_per_cycle',
            type: 'int'
        },
        {
            name: 'minimum_rent_quantity_per_cycle',
            type: 'int'
        },
        {
            name: 'minimum_rent_duration',
            type: 'int'
        },
        {
            name: 'maximum_rent_duration',
            type: 'int'
        },
        {
            name: 'faas_stage',
            type: 'auto'
        },
        {
            name: 'faas_months_to_harvest',
            type: 'int'
        },
        {
            name: 'faas_months_from_seedling',
            type: 'int'
        },
        {
            name: 'faas_current_stage_to_harvest_position',
            type: 'int'
        },
        {
            name: 'faas_maximum_number_of_stages_to_harvest',
            type: 'int'
        },
        {
            name: 'faas_maximum_number_of_months_to_harvest',
            type: 'int'
        },
        {
            name: 'faas_next_stage',
            type: 'string'
        },
        {
            name: 'faas_number_of_months_to_next_stage',
            type: 'int'
        },
        {
            name: 'is_faas_insured',
            type: 'boolean'
        },
        {
            name: 'faas_total_insurance_value',
            type: 'float'
        },
        {
            name: 'is_faas_tradable',
            type: 'boolean'
        },
        {
            name: 'faas_expected_total_produce',
            type: 'float'
        },
        {
            name: 'faas_must_be_held_to_maturity',
            type: 'boolean'
        },
        {
            name: 'faas_region',
            type: 'string'
        },
        {
            name: 'maximum_faas_duration',
            type: 'int'
        },
        {
            name: 'minimum_faas_duration',
            type: 'int'
        },
        {
            name: 'minimum_quantity_for_faas_subscription',
            type: 'int'
        },
        {
            name: 'maximum_quantity_for_faas_subscription',
            type: 'int'
        },
        {
            name: 'cumulative_quantity',
            type: 'int'
        },
        {
            name: 'date_current_stage_started',
            type: 'date'
        },
        {
            name: 'faas_month_season_started',
            type: 'string'
        },
        {
            name: 'faas_year_season_started',
            type: 'string'
        },
        {
            name: 'has_warranty',
            type: 'boolean'
        },
        {
            name: 'months_of_warranty',
            type: 'int'
        },
        {
            name: 'has_son_certification',
            type: 'boolean'
        },
        {
            name: 'has_nafdac_certification',
            type: 'boolean'
        },
        {
            name: 'other_certifications',
            type: 'string'
        },
        {
            name: 'faas_stage_activities',
            type: 'string'
        },
        {
            name: 'faas_insurance_coverage',
            type: 'string'
        },
        {
            name: 'faas_insurance_institution',
            type: 'string'
        },
        {
            name: 'nature_of_product',
            type: 'string'
        },
        {
            name: 'clothes_measurement_unit',
            type: 'string'
        },
        {
            name: 'clothes_type',
            type: 'string'
        },
        {
            name: 'clothes_material',
            type: 'string'
        },
        {
            name: 'clothes_colour',
            type: 'string'
        },
        {
            name: 'clothes_neck_size',
            type: 'float'
        },
        {
            name: 'clothes_hand_wrist_size',
            type: 'float'
        },
        {
            name: 'clothes_hand_length',
            type: 'float'
        },
        {
            name: 'clothes_stomach_size',
            type: 'float'
        },
        {
            name: 'clothes_shoulder_size',
            type: 'float'
        },
        {
            name: 'clothes_body_length',
            type: 'float'
        },
        {
            name: 'clothes_material_variation',
            type: 'string'
        },
        {
            name: 'clothes_neck_size_variation',
            type: 'string'
        },
        {
            name: 'clothes_hand_wrist_variation',
            type: 'string'
        },
        {
            name: 'clothes_hand_length_variation',
            type: 'string'
        },
        {
            name: 'clothes_stomach_size_variation',
            type: 'string'
        },
        {
            name: 'clothes_shoulder_size_variation',
            type: 'string'
        },
        {
            name: 'clothes_colour_variation',
            type: 'string'
        },
        {
            name: 'clothes_body_length_variation',
            type: 'string'
        },
        {
            name: 'clothes_hand_length_type',
            type: 'string'
        },
        {
            name: 'clothes_dimension_label',
            type: 'string'
        },
        {
            name: 'clothes_dimension_label_variation',
            type: 'string'
        },
        {
            name: 'clothes_trouser_length',
            type: 'float'
        },
        {
            name: 'clothes_waist_size',
            type: 'float'
        },
        {
            name: 'clothes_thigh_size',
            type: 'float'
        },
        {
            name: 'clothes_ankle_size',
            type: 'float'
        },
        {
            name: 'clothes_trouser_length_variation',
            type: 'string'
        },
        {
            name: 'clothes_trouser_size_variation',
            type: 'string'
        },
        {
            name: 'clothes_ankle_size_variation',
            type: 'string'
        },
        {
            name: 'clothes_is_designed_for',
            type: 'string'
        },
        {
            name: 'clothes_target_demography',
            type: 'string'
        },
        {
            name: 'shoes_measurement_unit',
            type: 'string'
        },
        {
            name: 'shoe_men_type',
            type: 'string'
        },
        {
            name: 'shoe_female_type',
            type: 'string'
        },
        {
            name: 'shoe_colour',
            type: 'string'
        },
        {
            name: 'shoe_size',
            type: 'string'
        },
        {
            name: 'shoe_colour_variation',
            type: 'string'
        },
        {
            name: 'shoe_size_variation',
            type: 'string'
        },
        {
            name: 'shoe_material',
            type: 'string'
        },
        {
            name: 'shoe_weight_variation',
            type: 'string'
        },
        {
            name: 'shoe_material_variation',
            type: 'string'
        },
        {
            name: 'shoe_sole_material',
            type: 'string'
        },
        {
            name: 'shoe_sole_material_variation',
            type: 'string'
        },
        {
            name: 'shoe_is_designed_for',
            type: 'string'
        },
        {
            name: 'shoe_target_demography',
            type: 'string'
        },
        {
            name: 'baby_shoes_age_range',
            type: 'string'
        },
        {
            name: 'suit_size',
            type: 'string'
        },
        {
            name: 'suit_colour',
            type: 'string'
        },
        {
            name: 'suit_colour_variation',
            type: 'string'
        },
        {
            name: 'suit_size_variation',
            type: 'string'
        },
        {
            name: 'image_dimension_width',
            type: 'float'
        },
        {
            name: 'image_dimension_height',
            type: 'float'
        },
        {
            name: 'image_dimension_capacity_in_mb',
            type: 'float'
        },
        {
            name: 'image_dimension_variation',
            type: 'string'
        },
        {
            name: 'image_measurement_unit',
            type: 'string'
        },
        {
            name: 'image_measurement_unit_symbol',
            type: 'string'
        },
        {
            name: 'image_format',
            type: 'string'
        },
        {
            name: 'footage_format',
            type: 'string'
        },
        {
            name: 'footage_dimension_capacity_in_mb',
            type: 'string'
        },
        {
            name: 'book_authors',
            type: 'string'
        },
        {
            name: 'book_edition',
            type: 'string'
        },
        {
            name: 'book_isbn',
            type: 'string'
        },
        {
            name: 'book_total_page',
            type: 'int'
        },
        {
            name: 'book_year_of_print',
            type: 'int'
        },
        {
            name: 'book_format',
            type: 'string'
        },
        {
            name: 'book_print_quality',
            type: 'string'
        },
        {
            name: 'book_target_demography',
            type: 'string'
        },
        {
            name: 'book_other_secondary_targets',
            type: 'string'
        },
        {
            name: 'book_writing_style',
            type: 'string'
        },
        {
            name: 'book_type',
            type: 'string'
        },
        {
            name: 'book_number_of_chapters',
            type: 'int'
        },
        {
            name: 'book_format_variation',
            type: 'string'
        },
        {
            name: 'book_edition_variation',
            type: 'string'
        },
        {
            name: 'product_variation_id',
            type: 'int'
        },
        {
            name: 'image_resolution',
            type: 'int'
        },
        {
            name: 'image_resolution_unit',
            type: 'string'
        },
        {
            name: 'image_resolution_variation',
            type: 'string'
        },
        {
            name: 'image_file_for_download',
            type: 'string'
        },
        {
            name: 'footage_quality_type',
            type: 'string'
        },
        {
            name: 'footage_scan_type',
            type: 'string'
        },
        {
            name: 'footage_scan_type_unit',
            type: 'string'
        },
        {
            name: 'footage_dimension_width',
            type: 'float'
        },
        {
            name: 'footage_dimension_height',
            type: 'float'
        },
        {
            name: 'footage_resolution',
            type: 'int'
        },
        {
            name: 'footage_aspect_ratio',
            type: 'string'
        },
        {
            name: 'footage_clip_length',
            type: 'float'
        },
        {
            name: 'footage_size',
            type: 'float'
        },
        {
            name: 'footage_frame_rate',
            type: 'float'
        },
        {
            name: 'footage_quality_type_variation',
            type: 'string'
        },
        {
            name: 'footage_aspect_ratio_variation',
            type: 'string'
        },
        {
            name: 'footage_resolution_variation',
            type: 'string'
        },
        {
            name: 'footage_file',
            type: 'string'
        },
        {
            name: 'book_softcopy_file',
            type: 'string'
        },
        {
            name: 'book_preview_file',
            type: 'string'
        },
        {
            name: 'footage_production_type',
            type: 'string'
        },
        {
            name: 'sound_format',
            type: 'string'
        },
        {
            name: 'sound_production_type',
            type: 'string'
        },
        {
            name: 'sound_file',
            type: 'string'
        },
        {
            name: 'sound_clip_length',
            type: 'string'
        },
        {
            name: 'sound_format_variation',
            type: 'string'
        },
        {
            name: 'clothes_chest_size',
            type: 'float'
        },
        {
            name: 'clothes_back_body_length',
            type: 'float'
        },
        {
            name: 'clothes_back_body_length_variation',
            type: 'string'
        },
        {
            name: 'clothes_chest_length_variation',
            type: 'string'
        },
        {
            name: 'clothes_baby_age_range',
            type: 'string'
        },
        {
            name: 'feature_1',
            type: 'string'
        },
        {
            name: 'feature_2',
            type: 'string'
        },
        {
            name: 'feature_3',
            type: 'string'
        },
        {
            name: 'feature_4',
            type: 'string'
        },
        {
            name: 'is_a_variation',
            type: 'string'
        }
    ]
});